[build]
  publish = "."
  functions = "netlify/functions"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  included_files = ["netlify/functions/data/**", "netlify/functions/services/**", "blockchain/**"]  # Added services/**

[[headers]]
  for = "/js/*"
  [headers.values]
    "Content-Type" = "application/javascript"
    "X-Content-Type-Options" = "nosniff"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[dev]
  publish = "."
  port = 8888
  autoLaunch = true
  functions = "netlify/functions"
  functionsPort = 8888

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200